// Mocks generated by Mockito 5.3.1 from annotations
// in weather_app/test/features/weather_app/data/repositories/weather_info_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/core/network/network_info.dart' as _i6;
import 'package:weather_app/features/weather_app/data/datasources/weather_info_local_data_source.dart'
    as _i5;
import 'package:weather_app/features/weather_app/data/datasources/weather_info_remote_datasource.dart'
    as _i3;
import 'package:weather_app/features/weather_app/data/models/weather_info_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherInfoModel_0 extends _i1.SmartFake
    implements _i2.WeatherInfoModel {
  _FakeWeatherInfoModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherInfoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherInfoRemoteDataSource extends _i1.Mock
    implements _i3.WeatherInfoRemoteDataSource {
  MockWeatherInfoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherInfoModel> getWeatherInfo(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherInfo,
          [city],
        ),
        returnValue:
            _i4.Future<_i2.WeatherInfoModel>.value(_FakeWeatherInfoModel_0(
          this,
          Invocation.method(
            #getWeatherInfo,
            [city],
          ),
        )),
      ) as _i4.Future<_i2.WeatherInfoModel>);
}

/// A class which mocks [WeatherInfoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherInfoLocalDataSource extends _i1.Mock
    implements _i5.WeatherInfoLocalDataSource {
  MockWeatherInfoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherInfoModel> getLastWeatherInfo() => (super.noSuchMethod(
        Invocation.method(
          #getLastWeatherInfo,
          [],
        ),
        returnValue:
            _i4.Future<_i2.WeatherInfoModel>.value(_FakeWeatherInfoModel_0(
          this,
          Invocation.method(
            #getLastWeatherInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.WeatherInfoModel>);
  @override
  _i4.Future<void> cacheWeatherInfo(_i2.WeatherInfoModel? weatherInfoToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeatherInfo,
          [weatherInfoToCache],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
